import '@/styles/globals.css';
import type { Metadata } from 'next';

import { cn } from '@/lib/utils';
import { fontSerif, fontSans } from '@/config/font';
import { SmoothScroll } from '@/components/smooth-scroll';
import { Header } from '@/components/header';
import { Hero } from '@/components/hero';
import { Footer } from '@/components/footer';

interface RootLayoutProps {
  readonly children: React.ReactNode;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body
        className={cn(
          'min-h-screen font-sans antialiased',
          fontSerif.variable,
          fontSans.variable,
        )}
      >
        <Header />
        <SmoothScroll>
          <Hero />
          {children}
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
